/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// Importing file input code
import java.io.IOException;
import java.io.File;
import java.util.Scanner;


/**
 *
 * @author 343084331
 */
public class MainMenu extends javax.swing.JFrame {
    
    // Array creation
    static EthicsCase [] cases = new EthicsCase[8];
    
    // Overloading constructor of verdict
    Verdict v = new Verdict("Customizable title","No verdict given","No reason given");    
        
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        // Counter variable to change array positon
        int counter = 0;
        // Making cases from the file 
        try {
            // Making scanner
            Scanner input = new Scanner(new File("Scenarios.txt"));
            
            // Loop to go through file
            while (input.hasNextLine() ) {
                // Splitting the file text
                String text = input.nextLine();
                String [] info = text.split(",");
                
                // Check for array position when scenario is a privacy case
                if (counter == 0 || counter == 4) {
                        // Making the case object
                    cases[counter] = new PrivacyCase (info[0].trim(), info[1].trim(), info[2].trim() );
                }
                // Check for array position when scenario is an algorithm case
                if (counter == 1 || counter == 5) {
                        // Making the case object
                    cases[counter] = new AlgorithmCase (info[0].trim(), info[1].trim(), info[2].trim() );
                }
                // Check for array position when scenario is a misinformation case
                if (counter == 2 || counter == 6) {
                        // Making the case object
                    cases[counter] = new MisinformationCase (info[0].trim(), info[1].trim(), info[2].trim() );
                }
                // Check for array position when scenario is an intellectual property case
                if (counter == 3 || counter == 7) {
                        // Making the case object
                    cases[counter] = new IntellectualPropertyCase (info[0].trim(), info[1].trim(), info[2].trim() );
                }       
                counter += 1; //Increasing counter to move array position
            }
            input.close();  //Closing scanner  
        // Error checking
        }
        catch ( IOException e) {
            System.out.print("Error with reading from file");
        }
        catch (ArrayIndexOutOfBoundsException f) {
            System.out.println("Array error");           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ethics evaluator");

        jButton1.setText("Go to evaluation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Where do you stand on  this scale? ");

        jLabel3.setText("Tech optimist");

        jLabel4.setText("Cautious realist");

        jLabel5.setText("Critical thinker");

        jLabel6.setText("Ethics watchdog");

        jButton2.setText("Sites for more info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new Scenario1().setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // Count variable to change array positon
        int count = 0;
        // Displaying sites for info
        try {
            // Making scanner
            Scanner input = new Scanner(new File("sites.txt"));
            
            // Loop to go through file
            while (input.hasNextLine() ) {
                // Splitting the file text
                String text = input.nextLine();
                String [] info = text.split(",");
                // Displaying text
                System.out.println("To learn more about " + info[0] + ":" + info[1]);
                // Increasing count
                count += 1;
           
            }
            input.close();  //Closing scanner  
        // Error checking
        }
        catch ( IOException e) {
            System.out.print("Error with reading from file");
        }
        catch (ArrayIndexOutOfBoundsException f) {
            System.out.println("Array error");           
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
