/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// Importing file input code
import java.io.IOException;
import java.io.File;
import java.util.Scanner;


/**
 *
 * @author 343084331
 */
public class MainMenu extends javax.swing.JFrame {
    
    // Array creation
    static EthicsCase [] cases = new EthicsCase[8];
        
        
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        
        /**
        // Premade cases
        cases[0] = new PrivacyCase ("The always-on microphone", 
                "A smartphone company recorded household conversation even when the device " +
                "was not activated. Employees reviewed the recording", "audio recordings");
                
        cases[1] = new AlgorithmCase ("The biased hiring bot", "A tech company's AI screening " +
                "tool ranked male applicants higher than equally qualfiied female applicants.", "gender bias");
        
        cases[2] = new MisinformationCase ("The deepfake politication", "A deepfake video of a candidate " +
                "saying things they never said spread widely online during an election before being identified as fake.",
                "deepfake video");
        
        cases[3] = new IntellectualPropertyCase ("AI trained on artist work", "An AI image generator was trained on millions " +
                "of artworks scraped without permission. Artists receive no credit or payment.", "AI-generated art");
        
        // new cases
        cases[4] = new PrivacyCase ("The data breech", "A company collected data on users to get feedback for their product. " +
                "A hack found a security flaw and uncovered the data. The hacker gave suggestion on how to improve the data security.",
                "data breech");
        
        cases[5] = new AlgorithmCase ("The healthcare diagonsis", "A hospital used AI to speed up their diagonsis of patients " +
                "which let them deal with more people. Minorities were more likely to be misdiagnosed due to lack of representation in the algorithm.",
                "Healthcase diagnosis");
        
        cases[6] = new MisinformationCase ("The health posts", "An influencer creates a post about a disease outbreak without research " + 
                "and ends up posting incorrect info. Their followers trust them and repost the content leading to misinformation spreading.",
                "social media post");
        
        cases[7] = new IntellectualPropertyCase ("The missing show", "A streaming platform removes a show after underperforming in profits, " +
                "users pirate the show after removal in order to watch the show.", "digital piracy");
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Start evaluation");

        jButton1.setText("Go to evaluation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Making cases from the file 
        try {
            // Making scanner
            Scanner input = new Scanner(new File("Scenarios.txt"));
            
            // Loop to go through file
            while (input.hasNextLine() ) {
                // Splitting the file text
                String text = input.nextLine();
                String [] info = text.split(",");
                // Loop to go through fill in each case in cases array
                for (int i = 0 ; i < cases.length ; i++ ) {
                    // Check for array position when scenario is a privacy case
                    if (i == 0 || i == 4) {
                        // Making the case object
                        cases[i] = new PrivacyCase (info[i].trim(), info[i+1].trim(), info[i+2].trim() );
                    }
                }
            input.close();  //Closing scanner  
            }
        }
        catch ( IOException e) {
            System.out.print("Error with reading from file");
        }
        
        new Scenario1().setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
